version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - koconder
  ignore:
  - dependency-name: php
    versions:
    - 8.0.1.pre.fpm
    - 8.0.2.pre.fpm
